stages:
  - build
  - deploy

# ---------- FRONTEND : build + déploiement sur GitLab Pages ----------
pages:
  stage: deploy
  image: node:20
  rules:
    - changes:
        - frontend/**/*
      if: '$CI_COMMIT_BRANCH == "main"'
  script:
    - cd frontend
    - echo "VITE_API_URL=$VITE_API_URL" > .env
    - npm install
    - npm run build
    - cp -r dist ../public
  artifacts:
    paths:
      - public
  cache:
    paths:
      - frontend/node_modules/